backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "portfolio"
    label: "포트폴리오"
    folder: "content/portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "카테고리", name: "category", widget: "select", options: ["ai-visual", "promo", "etc", "customer"]}
      - {label: "썸네일 이미지", name: "thumbnail", widget: "image"}
      - {label: "설명", name: "description", widget: "text", required: false}
      - {label: "상세 이미지들", name: "images", widget: "list", field: {label: "이미지", name: "image", widget: "image"}}
      - {label: "게시일", name: "date", widget: "datetime"}
